video_path: "/media/david/media/TFM/dataset/videos"
excels_path: "/media/david/media/TFM/dataset/excels"
species_dataset: "/media/david/media/TFM/dataset/images"
bottom_dataset: "/media/david/media/TFM/dataset/bottom"
output_path: "/media/david/media/TFM/experiments"
model_path: "/media/david/media/TFM/models"

species: ["Spatangus purpureus",
          "Echinaster sepositus",
          "Cerianthus membranaceus",
          "Bonellia viridis",
          "Scyliorhinus canicula",
          "Ophiura ophiura",
          "Background"]

species_classification:
  model: "convnext_large"
  batch_size: 12
  num_epochs: 30
  img_per_annot: 5
  learning_rate: 0.0005
  num_workers: 12
  load_model: false
  save_model: true
  pin_memory: true