video_path: ""
excels_path: ""
icm_dataset_path: "/media/david/media/ICM20-1"
output_path: "/media/david/media/TFM/experiments"
model_path: "/media/david/media/TFM/models"

wandb: false
model: "efficientnet_b0"
batch_size: 12
num_epochs: 30
learning_rate: 0.00001
num_workers: 12
load_model: false
save_model: true
pin_memory: true

species: ["Spatangus purpureus",
          "Echinaster sepositus",
          "Cerianthus membranaceus",
          "Bonellia viridis",
          "Scyliorhinus canicula",
          "Ophiura ophiura",
          "Background"]
