video_path: ""
excels_path: ""
icm_dataset_path: "/media/david/media/ICM20-1"
output_path: "/media/david/media/Uncertainty/Experiments"
model_path: "/media/david/media/Uncertainty/Models"

wandb: true
model: "efficientnet_b0"
batch_size: 12
num_epochs: 100
learning_rate: 0.00001
num_workers: 12
load_model: true
save_model: false
pin_memory: true

species: ["Spatangus purpureus",
          "Echinaster sepositus",
          "Cerianthus membranaceus",
          "Bonellia viridis",
          "Scyliorhinus canicula",
          "Ophiura ophiura",
          "Background"]
