dataset: "/media/david/Uncertainty/article_dataset_v2"
models: "/media/david/Uncertainty/weights"
device: "cuda"
classes: ["spatangus_purpureus",
          "echinaster_sepositus",
          "cerianthus_membranaceus",
          "bonellia_viridis",
          "scyliorhinus_canicula",
          "ophiura_ophiura",
          "background"]
wandb:
  params:
    project: "ICM-Article"
    entity: "davidserra9"