dataset: "/home/dserrano/shared/article_dataset"
models: "/home/dserrano/shared/weights/TFM"
device: "cuda"
classes: ["spatangus_purpureus",
          "echinaster_sepositus",
          "cerianthus_membranaceus",
          "bonellia_viridis",
          "scyliorhinus_canicula",
          "ophiura_ophiura",
          "background"]
wandb:
  params:
    project: "ICM-Article"
    entity: "davidserra9"